### ISSUE TITLE
Error when syncing

### ISSUE THREAD

**Issue by jonathanglasmeyer** [bgilbert6/lingq-syncer#1]
Hi, 
thanks for this tool, very handy!
I just tried syncing, and am now getting this error:
<img width="218" alt="Screenshot 2023-02-06 at 12 23 35" src="https://user-images.githubusercontent.com/3755413/216959605-13de6be1-0a1e-41f2-b12e-3b5adc81fe73.png">
I've tried deleting and reinstalling the plugin, but the error occurs again.
Any pointers?
Thx!

**Comment by bgilbert6** [comment]
Is this a new error and it used to work? Maybe a change with lingqs API, I can take a look

**Comment by jonathanglasmeyer** [comment]
Yea, it's new. I used to be able to sync successfully some days ago.

**Comment by jonathanglasmeyer** [comment]
Debugged a bit. 
```python
Traceback (most recent call last):
  File "concurrent.futures.thread", line 52, in run
  File "aqt.operations", line 239, in wrapped_op
  File "/Users/jonathan.glasmeyer/Library/Application Support/Anki2/addons21/98811431/plugin.py", line 175, in <lambda>
    op=lambda col: retrieve_vocab(api_key),
  File "/Users/jonathan.glasmeyer/Library/Application Support/Anki2/addons21/98811431/plugin.py", line 164, in retrieve_vocab
    raise exc
  File "/Users/jonathan.glasmeyer/Library/Application Support/Anki2/addons21/98811431/plugin.py", line 142, in retrieve_vocab
    result = get_all_cards(api_key)
  File "/Users/jonathan.glasmeyer/Library/Application Support/Anki2/addons21/98811431/lingq.py", line 59, in get_all_cards
    lessons = get_lessons(api_key, language, course["pk"])
KeyError: 'pk'
```

When `print`-ing the `course`, it gives me 
```
{'id': 1223502, 'title': 'Quick Imports', 'imageUrl': 'https://static.lingq.com/media/resources/collections/images/2023/01/29/qi-s-26d69637.webp'}
```
On first glance, the `pk` field doesn't seem to be there, rather we find a field called `id` now. 

Changing [L58](https://github.com/bgilbert6/lingq-syncer/blob/master/addon/lingq.py#L58) to
```
lessons = get_lessons(api_key, language, course["id"])
```
makes the plugin work again for me.
